// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Shopkeeper.Api.Data;

#nullable disable

namespace Shopkeeper.Api.Migrations
{
    [DbContext(typeof(ShopkeeperDbContext))]
    [Migration("20260308152000_ShopDiscountSettings")]
    partial class ShopDiscountSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot intentionally minimal — regenerate with:
            //   dotnet ef migrations add <NextMigration>
        }
    }
}
